name: Build Step

on:
  push:
    branches: ["main"]

jobs:  
  build-and-push-docker:
    name: Buiild Docker Image and Push to Docker Repository

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout Stage
        uses: actions/checkout@v3
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ewr.vultrcr.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setting required folders to packages/site
        run: |
          sudo apt update -y && sudo apt install curl unzip
          curl -L "${{secrets.FABSTIR_LIB_URL}}" --output fabstirdb-lib.tgz
          cp ./fabstirdb-lib.tgz ./packages/site/
          
          curl -L "${{secrets.PUBLIC_ASSETS_URL}}" --output public.zip
          unzip public.zip
          cp -r ./public ./packages/site

          curl -L "${{secrets.CONTRACTS_ZIP_URL}}" --output contracts.zip
          unzip contracts.zip
          cp -r ./contracts ./packages/site/
          
          ## cleanup
          rm -rf ./public ./contracts
          rm contracts.zip public.zip fabstirdb-lib.tgz

      - name: Set env
        run: | 
          echo "${{secrets.ENV_FILE}}" > packages/site/.env.local
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ewr.vultrcr.com/fabstir/mp:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Fabstir/gitops-fabstir-media-player
          ref: 'main'
          ssh-key: ${{ secrets.GITOPS_REPO_SSH_PRIVATE_KEY }}
      - name: Setup Git Config
        run: |
          git config user.email "ammarkhaliq@gmail.com"
          git config user.name "Ammar Haider"
          sed -i "s#ewr.vultrcr.com.*#ewr.vultrcr.com/fabstir/mp:${{github.sha}}#g" fabstir-mp/deployment.yaml
          git add -A
          git commit -am "Update image for ${{github.sha}}"
      - name: Pushing Updated Image Tag
        run: git push origin main
          
