name: Build Step

on:
  push:
    branches-ignore: ["main"]
  

jobs:  
  build-and-push-docker:
    name: Buiild Docker Image and Push to Docker Repository

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout Stage
        uses: actions/checkout@v3
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ewr.vultrcr.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setting required folders to packages/site
        run: |
          sudo apt update -y && sudo apt install curl unzip
          curl -L "${{secrets.FABSTIR_LIB_URL}}" --output fabstirdb-lib-v1.0.146.tgz
          cp ./fabstirdb-lib-v1.0.146.tgz ./packages/site/
          
          curl -L "${{secrets.PUBLIC_ASSETS_URL}}" --output public.zip
          unzip public.zip
          cp -r ./public ./packages/site

          curl -L "${{secrets.CONTRACTS_ZIP_URL}}" --output contracts.zip
          unzip contracts.zip
          cp -r ./contracts ./packages/site/
          
          ## cleanup
          rm -rf ./public ./contracts
          rm contracts.zip public.zip fabstirdb-lib-v1.0.146.tgz
    
      - name: Build
        run: docker build .